import folium
import json
import os

def generate_urban_mesh_map():
    # Center around the geometric center of Iran
    map_center = [32.4279, 53.6880]
    mesh_map = folium.Map(location=map_center, zoom_start=5, tiles="CartoDB positron")

    # Load the scraped data generated by Playwright
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    json_path = os.path.join(base_dir, "data", "active_zones.json")
    
    try:
        with open(json_path, 'r', encoding='utf-8') as f:
            active_zones = json.load(f)
            print(f"Loaded {len(active_zones)} zones from {json_path}")
            
            # Plot each zone from the JSON on the map
            for zone in active_zones:
                folium.CircleMarker(
                    location=[zone['lat'], zone['lon']],
                    radius=zone.get('radius_km', 5),
                    color=zone.get('color', 'red'),
                    fill=True,
                    fill_color=zone.get('color', 'red'),
                    fill_opacity=0.7,
                    tooltip=zone.get('zone_name', 'Unknown Zone')
                ).add_to(mesh_map)
                
    except FileNotFoundError:
        print(f"Warning: Data file not found at {json_path}. Drawing empty map.")
    except Exception as e:
        print(f"Error parsing JSON data: {e}")

    # Save the HTML file
    output_filename = "mesh_map_base.html"
    mesh_map.save(output_filename)
    print(f"Generated base map: {output_filename}")

if __name__ == "__main__":
    generate_urban_mesh_map()
